### ISSUE TITLE
admin_bdy branch: add logging and email reporting

### ISSUE THREAD

**Issue by billgeo** [linz/download_ta_bdys#10]
Will need to notify linzdataservadmin@linz.govt.nz and addressing@linz.govt.nz when this is run with suitable information. Will need to make it clear whether processing was successful or not.

**Comment by josephramsay** [comment]
Uses existing logging from the original download_ta_bdys. Do you want a rewrite?

**Comment by billgeo** [comment]
@josephramsay Can we send the log + a success/fail message to multiple email accounts?

**Comment by josephramsay** [comment]
yep, original code uses python logger to do this. I do a similar thing with the dvl_checker.
