### ISSUE TITLE
admin_bdy branch: run AIMS database functions

### ISSUE THREAD

**Issue by billgeo** [linz/download_ta_bdys#11]
Final step in the process is to run the AIMS database functions for updating reference data. Will need to check the return codes and raise message appropriately.

fnreferencedataupdatelocality
fnreferencedataupdatemeshblock

**Comment by josephramsay** [comment]
Using sh script to coordinate. Have comment/added these but only populating temp table (not table in admin_bdy schema) will need go-ahead before a run. See last push

**Comment by billgeo** [comment]
Great.
