### ISSUE TITLE
admin_bdy branch: incrementally update data

### ISSUE THREAD

**Issue by billgeo** [linz/download_ta_bdys#12]
Data should be imported incrementally, i.e. only import changes to the data based on primary key (don't truncate and insert). 

Use the functions from the table versioning extensions to create a diff and then apply it. Would suggest importing to a temp table first.

ver_get_table_differences
ver_apply_table_differences

**Comment by ghost** [comment]
@billgeo Ref data download script generates raw input data to schema admin_bdys_import on dev so you can take a look if you want. Planning to run validation over these and transfer to admin_bdys schema. One issue I am just noticing. Localities is generating a lot of errors. what should be the fix here? Just report the errors and move on? I imagine it will screw up the aims ref_data if we do that. 

The error is caught using the existing fix_esri_polygon() function so I'm guessing this is a regular occurrence?

problem with feature 231 geom
problem with feature 458 geom
problem with feature 524 geom
problem with feature 531 geom
problem with feature 583 geom
problem with feature 744 geom
problem with feature 789 geom
problem with feature 835 geom
problem with feature 944 geom
problem with feature 1076 geom
problem with feature 1159 geom
problem with feature 1190 geom
problem with feature 1234 geom
problem with feature 1360 geom
problem with feature 1376 geom
problem with feature 1409 geom
problem with feature 1484 geom
problem with feature 1491 geom
problem with feature 1492 geom
problem with feature 1508 geom
problem with feature 1595 geom
problem with feature 1603 geom
problem with feature 1754 geom
problem with feature 1755 geom
problem with feature 1759 geom
problem with feature 1762 geom
problem with feature 1766 geom
problem with feature 1775 geom
problem with feature 1776 geom
problem with feature 1778 geom
problem with feature 1779 geom
problem with feature 1782 geom
problem with feature 1787 geom
problem with feature 1791 geom
problem with feature 1802 geom
problem with feature 1806 geom
problem with feature 1807 geom
problem with feature 1818 geom
problem with feature 1819 geom
problem with feature 1823 geom
problem with feature 1829 geom
problem with feature 1830 geom
problem with feature 1837 geom
problem with feature 1840 geom
problem with feature 1845 geom
problem with feature 1847 geom
problem with feature 1850 geom
problem with feature 1867 geom
problem with feature 1870 geom
problem with feature 1878 geom
problem with feature 1881 geom
problem with feature 1886 geom
problem with feature 1890 geom
problem with feature 1896 geom
problem with feature 1918 geom
problem with feature 1923 geom
problem with feature 1925 geom
problem with feature 1927 geom
problem with feature 1930 geom
problem with feature 1931 geom
problem with feature 1934 geom
problem with feature 1946 geom
problem with feature 1947 geom
problem with feature 1966 geom
problem with feature 1969 geom
problem with feature 1970 geom
problem with feature 1973 geom
problem with feature 1976 geom
problem with feature 1977 geom
problem with feature 1991 geom
problem with feature 2007 geom
problem with feature 2012 geom
problem with feature 2040 geom
problem with feature 2045 geom
problem with feature 2053 geom
problem with feature 2055 geom
problem with feature 2057 geom
problem with feature 2064 geom
problem with feature 2065 geom
problem with feature 2072 geom
problem with feature 2077 geom
problem with feature 2083 geom
problem with feature 2085 geom
problem with feature 2089 geom
problem with feature 2106 geom
problem with feature 2107 geom
problem with feature 2112 geom
problem with feature 2116 geom
problem with feature 2117 geom
problem with feature 2131 geom
problem with feature 2147 geom
problem with feature 2149 geom
problem with feature 2167 geom
problem with feature 2188 geom
problem with feature 2213 geom
problem with feature 2214 geom
problem with feature 2220 geom
problem with feature 2228 geom
problem with feature 2229 geom
problem with feature 2291 geom
problem with feature 2294 geom
problem with feature 2310 geom
problem with feature 2348 geom
problem with feature 2389 geom
problem with feature 2407 geom
problem with feature 2411 geom
problem with feature 2415 geom
problem with feature 2421 geom
problem with feature 2422 geom
problem with feature 2438 geom
problem with feature 2447 geom
problem with feature 2451 geom
problem with feature 2453 geom
problem with feature 2456 geom
problem with feature 2460 geom
problem with feature 2489 geom
problem with feature 2493 geom
problem with feature 2496 geom
problem with feature 2510 geom
problem with feature 2595 geom
problem with feature 2632 geom
problem with feature 2644 geom
problem with feature 2691 geom
problem with feature 2717 geom
problem with feature 2725 geom
problem with feature 2742 geom
problem with feature 2746 geom
problem with feature 2815 geom
problem with feature 2961 geom
problem with feature 2972 geom
problem with feature 3033 geom
problem with feature 3116 geom
problem with feature 3215 geom
problem with feature 3320 geom
problem with feature 3389 geom
problem with feature 3413 geom
problem with feature 3447 geom
problem with feature 3450 geom
problem with feature 3471 geom
problem with feature 3482 geom
problem with feature 3483 geom
problem with feature 3484 geom
problem with feature 3485 geom
problem with feature 3486 geom
problem with feature 3487 geom
problem with feature 3488 geom
problem with feature 3489 geom
problem with feature 3490 geom
problem with feature 3491 geom
problem with feature 3492 geom
problem with feature 3493 geom
problem with feature 3494 geom
problem with feature 3495 geom
problem with feature 3496 geom
problem with feature 3497 geom
problem with feature 3498 geom
problem with feature 3499 geom
problem with feature 3500 geom
problem with feature 3501 geom
problem with feature 3502 geom
problem with feature 3503 geom
problem with feature 3504 geom
problem with feature 3505 geom
problem with feature 3506 geom
problem with feature 3507 geom
problem with feature 3508 geom
problem with feature 3509 geom
problem with feature 3510 geom
problem with feature 3511 geom
problem with feature 3518 geom
problem with feature 3520 geom
problem with feature 3521 geom
problem with feature 3522 geom
problem with feature 3530 geom
problem with feature 3531 geom
problem with feature 3533 geom
problem with feature 3539 geom
problem with feature 3540 geom
problem with feature 3544 geom
problem with feature 3545 geom
problem with feature 3546 geom
problem with feature 3549 geom
problem with feature 3550 geom
problem with feature 3553 geom
problem with feature 3554 geom
problem with feature 3555 geom
problem with feature 3556 geom
problem with feature 3563 geom
problem with feature 3569 geom
problem with feature 3570 geom
problem with feature 3574 geom
problem with feature 3575 geom
problem with feature 3578 geom
problem with feature 3585 geom
problem with feature 3586 geom
problem with feature 3588 geom
problem with feature 3589 geom
problem with feature 3591 geom
problem with feature 3594 geom
problem with feature 3595 geom
problem with feature 3596 geom
problem with feature 3599 geom
problem with feature 3602 geom
problem with feature 3608 geom
problem with feature 3612 geom
problem with feature 3613 geom
problem with feature 3614 geom
problem with feature 3650 geom
problem with feature 3677 geom
problem with feature 3712 geom
problem with feature 3713 geom
problem with feature 3714 geom
problem with feature 3745 geom
problem with feature 3835 geom
problem with feature 3965 geom
problem with feature 4123 geom
problem with feature 4126 geom
problem with feature 4127 geom
problem with feature 4158 geom
problem with feature 4350 geom
problem with feature 4382 geom
problem with feature 4410 geom
problem with feature 4448 geom
problem with feature 4451 geom
problem with feature 4454 geom
problem with feature 4480 geom
problem with feature 4557 geom
problem with feature 4558 geom
problem with feature 4559 geom
problem with feature 4561 geom
problem with feature 4562 geom
problem with feature 4563 geom
problem with feature 4564 geom
problem with feature 4565 geom
problem with feature 4566 geom
problem with feature 4567 geom
problem with feature 4568 geom
problem with feature 4569 geom
problem with feature 4570 geom
problem with feature 4571 geom
problem with feature 4572 geom
problem with feature 4573 geom
problem with feature 4574 geom
problem with feature 4575 geom
problem with feature 4577 geom
problem with feature 4578 geom
problem with feature 4579 geom
problem with feature 4580 geom
problem with feature 4581 geom
problem with feature 4582 geom
problem with feature 4583 geom
problem with feature 4584 geom
problem with feature 4585 geom
problem with feature 4586 geom
problem with feature 4587 geom
problem with feature 4588 geom
problem with feature 4589 geom
problem with feature 4590 geom
problem with feature 4591 geom
problem with feature 4592 geom
problem with feature 4593 geom
problem with feature 4594 geom
problem with feature 4595 geom
problem with feature 4596 geom
problem with feature 4597 geom
problem with feature 4598 geom
problem with feature 4599 geom
problem with feature 4600 geom
problem with feature 4601 geom
problem with feature 4602 geom
problem with feature 4603 geom
problem with feature 4604 geom
problem with feature 4605 geom
problem with feature 4606 geom
problem with feature 4607 geom
problem with feature 4608 geom
problem with feature 4609 geom
problem with feature 4610 geom
problem with feature 4611 geom
problem with feature 4612 geom
problem with feature 4613 geom
problem with feature 4614 geom
problem with feature 4615 geom
problem with feature 4616 geom
problem with feature 4617 geom
problem with feature 4618 geom
problem with feature 4619 geom
problem with feature 4620 geom
problem with feature 4622 geom
problem with feature 4623 geom
problem with feature 4626 geom
problem with feature 4627 geom
problem with feature 4628 geom
problem with feature 4629 geom
problem with feature 4630 geom
problem with feature 4632 geom
problem with feature 4633 geom
problem with feature 4634 geom
problem with feature 4635 geom
problem with feature 4636 geom
problem with feature 4637 geom
problem with feature 4638 geom
problem with feature 4640 geom
problem with feature 4641 geom
problem with feature 4642 geom
problem with feature 4643 geom
problem with feature 4644 geom
problem with feature 4645 geom
problem with feature 4646 geom
problem with feature 4647 geom
problem with feature 4648 geom
problem with feature 4649 geom
problem with feature 4650 geom
problem with feature 4652 geom
problem with feature 4654 geom
problem with feature 4655 geom
problem with feature 4656 geom
problem with feature 4657 geom
problem with feature 4658 geom
problem with feature 4659 geom
problem with feature 4660 geom
problem with feature 4661 geom
problem with feature 4662 geom
problem with feature 4663 geom
problem with feature 4664 geom
problem with feature 4665 geom
problem with feature 4666 geom
problem with feature 4667 geom
problem with feature 4668 geom
problem with feature 4669 geom
problem with feature 4670 geom
problem with feature 4671 geom
problem with feature 4672 geom
problem with feature 4673 geom
problem with feature 4674 geom
problem with feature 4675 geom
problem with feature 4676 geom
problem with feature 4677 geom
problem with feature 4678 geom
problem with feature 4679 geom
problem with feature 4680 geom
problem with feature 4681 geom
problem with feature 4682 geom
problem with feature 4683 geom
problem with feature 4684 geom
problem with feature 4685 geom
problem with feature 4686 geom
problem with feature 4687 geom
problem with feature 4688 geom
problem with feature 4689 geom
problem with feature 4690 geom
problem with feature 4691 geom
problem with feature 4692 geom
problem with feature 4693 geom
problem with feature 4694 geom
problem with feature 4695 geom
problem with feature 4697 geom
problem with feature 4698 geom
problem with feature 4699 geom
problem with feature 4700 geom
problem with feature 4701 geom
problem with feature 4702 geom
problem with feature 4703 geom
problem with feature 4704 geom
problem with feature 4705 geom
problem with feature 4710 geom
problem with feature 4713 geom
problem with feature 4724 geom
problem with feature 4736 geom
problem with feature 4745 geom
problem with feature 4747 geom
problem with feature 4753 geom
problem with feature 4817 geom
problem with feature 4823 geom
problem with feature 5051 geom
problem with feature 5086 geom
problem with feature 5131 geom
problem with feature 5241 geom
problem with feature 5270 geom
problem with feature 5468 geom
problem with feature 5519 geom
problem with feature 5589 geom
problem with feature 5930 geom
problem with feature 5963 geom
problem with feature 6016 geom
problem with feature 6114 geom
problem with feature 6167 geom
problem with feature 6187 geom
problem with feature 6200 geom
problem with feature 6201 geom
problem with feature 6202 geom
problem with feature 6488 geom
problem with feature 6498 geom
problem with feature 6524 geom
problem with feature 6562 geom
problem with feature 6578 geom
problem with feature 6592 geom
problem with feature 6593 geom
problem with feature 6619 geom
problem with feature 6647 geom
problem with feature 6649 geom
problem with feature 6697 geom
problem with feature 6712 geom
problem with feature 6716 geom
problem with feature 6720 geom
problem with feature 6721 geom
problem with feature 6722 geom
problem with feature 6723 geom
problem with feature 6724 geom
problem with feature 6725 geom
problem with feature 6727 geom
problem with feature 6728 geom
problem with feature 6750 geom
problem with feature 6751 geom
problem with feature 6761 geom
problem with feature 6786 geom
problem with feature 6864 geom
problem with feature 6906 geom
problem with feature 6917 geom
problem with feature 6919 geom
problem with feature 6920 geom
problem with feature 6921 geom
problem with feature 6923 geom
problem with feature 6995 geom
problem with feature 7005 geom
problem with feature 7015 geom
problem with feature 7018 geom
problem with feature 7022 geom
problem with feature 7023 geom
problem with feature 7050 geom
problem with feature 7107 geom
problem with feature 7116 geom
problem with feature 7159 geom
problem with feature 7160 geom
problem with feature 7167 geom
problem with feature 7179 geom
problem with feature 7190 geom
problem with feature 7222 geom
problem with feature 7261 geom
problem with feature 7278 geom
problem with feature 7290 geom
problem with feature 7293 geom
problem with feature 7296 geom
problem with feature 7297 geom
problem with feature 7312 geom
problem with feature 7313 geom
problem with feature 7351 geom

**Comment by billgeo** [comment]
Hey @josephramsay. Will have a look today. Definitely don't want report those errors and move on. Will need to find out what the issue is and provide a fix. Probably some edge case that Jeremy didn't cover off in his original code.

**Comment by ghost** [comment]
@billgeo responding to @palmerj 's email, if I bypass the fix_esri_polygon code the script segfaults, I was assuming the two issues we're related/bad data, but maybe not. Will experiment with some combinations

**Comment by ghost** [comment]
Have found a solution where I discard all shift/fix functions and force all poly's to multi regardless of detected type. (setgeometrydirectly made no difference)

**Comment by palmerj** [comment]
Great. However but I think the shoft process is still required as we need all lat/long geoms in 0-360 space like the rest of BDE data.

**Comment by ghost** [comment]
TODO
Drop SFTP download method, create mount and read meshblock files directly ( have included shift_geom back into process). 
Column mapping and updates, see https://github.com/linz/postgresql-tableversion/issues/4

**Comment by josephramsay** [comment]
Getting an error running apply_table_differences() after mapping columns. Running the apply diffs func completes outside function. (See sql in last commit)

NOTICE:  1.1 create table admin_bdys_import.m_statsnz_ta as select \* from admin_bdys_import.temp_statsnz_ta
NOTICE:  1.2 alter table admin_bdys_import.m_statsnz_ta rename column geom to shape
NOTICE:  2.1 set search_path to admin_bdys,admin_bdys_import,public
NOTICE:  2.2 select addgeometrycolumn('m_statsnz_ta','temp',4167, 'MULTIPOLYGON', 2)
NOTICE:  2.3 update admin_bdys_import.m_statsnz_ta set temp = st_transform( st_setsrid(shape,4167),4167)
NOTICE:  2.4 alter table admin_bdys_import.m_statsnz_ta drop column shape
NOTICE:  2.5 alter table admin_bdys_import.m_statsnz_ta rename column temp to shape
NOTICE:  3.1 alter table admin_bdys_import.m_statsnz_ta drop column ta_code
NOTICE:  4.1 alter table admin_bdys_import.m_statsnz_ta add primary key (ogc_fid)
NOTICE:  5.1 create table admin_bdys_import.s_statsnz_ta as select \* from admin_bdys.territorial_authority
NOTICE:  5.2 alter table admin_bdys_import.s_statsnz_ta add primary key (ogc_fid)
NOTICE:  5.3 select table_version.ver_apply_table_differences('admin_bdys_import.s_statsnz_ta','admin_bdys_import.m_statsnz_ta','ogc_fid')
NOTICE:  Generating difference data for s_statsnz_ta
CONTEXT:  SQL statement "select table_version.ver_apply_table_differences('admin_bdys_import.s_statsnz_ta','admin_bdys_import.m_statsnz_ta','ogc_fid')"
PL/pgSQL function import_admin_boundary(character varying) line 137 at EXECUTE statement
ERROR:  Error executing template SQL: 
        CREATE TEMP TABLE table_diff AS
        SELECT
            T.id,
            T.action
        FROM
            table_version.ver_get_table_differences(
                's_statsnz_ta', 'm_statsnz_ta', 'ogc_fid'
            ) AS T (action CHAR(1), id integer)
        ORDER BY
            T.action,
            T.id;

Error: Failed comparing tables
PL/pgSQL function table_version.ver_get_table_differences(regclass,regclass,name) line 86 at IF
SQL statement "
        CREATE TEMP TABLE table_diff AS
        SELECT
            T.id,
            T.action
        FROM
            table_version.ver_get_table_differences(
                's_statsnz_ta', 'm_statsnz_ta', 'ogc_fid'
            ) AS T (action CHAR(1), id integer)
        ORDER BY
            T.action,
            T.id;
        "
PL/pgSQL function table_version.ver_executetemplate(text,text[]) line 8 at EXECUTE statement
SQL statement "SELECT table_version.ver_ExecuteTemplate( $sql$
        CREATE TEMP TABLE table_diff AS
        SELECT
            T.id,
            T.action
        FROM
            table_version.ver_get_table_differences(
                '%1%', '%2%', '%3%'
            ) AS T (action CHAR(1), id %4%)
        ORDER BY
            T.action,
            T.id;
        $sql$,
        ARRAY[
            p_original_table::TEXT,
            p_new_table::TEXT,
            p_key_column::TEXT,
            table_version.ver_table_key_datatype(p_original_table, p_key_column)
        ]
    )"
PL/pgSQL function table_version.ver_apply_table_differences(regclass,regclass,name) line 8 at PERFORM
SQL statement "select table_version.ver_apply_table_differences('admin_bdys_import.s_statsnz_ta','admin_bdys_import.m_statsnz_ta','ogc_fid')"
PL/pgSQL function import_admin_boundary(character varying) line 137 at EXECUTE statement
ERROR: type of parameter 26 (integer) does not match that when preparing the plan (character varying)
CONTEXT:  SQL statement "SELECT table_version.ver_ExecuteTemplate( $sql$
        CREATE TEMP TABLE table_diff AS
        SELECT
            T.id,
            T.action
        FROM
            table_version.ver_get_table_differences(
                '%1%', '%2%', '%3%'
            ) AS T (action CHAR(1), id %4%)
        ORDER BY
            T.action,
            T.id;
        $sql$,
        ARRAY[
            p_original_table::TEXT,
            p_new_table::TEXT,
            p_key_column::TEXT,
            table_version.ver_table_key_datatype(p_original_table, p_key_column)
        ]
    )"
PL/pgSQL function table_version.ver_apply_table_differences(regclass,regclass,name) line 8 at PERFORM
SQL statement "select table_version.ver_apply_table_differences('admin_bdys_import.s_statsnz_ta','admin_bdys_import.m_statsnz_ta','ogc_fid')"
PL/pgSQL function import_admin_boundary(character varying) line 137 at EXECUTE statement
*********\* Error **********

ERROR: Error executing template SQL: 
        CREATE TEMP TABLE table_diff AS
        SELECT
            T.id,
            T.action
        FROM
            table_version.ver_get_table_differences(
                's_statsnz_ta', 'm_statsnz_ta', 'ogc_fid'
            ) AS T (action CHAR(1), id integer)
        ORDER BY
            T.action,
            T.id;

Error: Failed comparing tables
PL/pgSQL function table_version.ver_get_table_differences(regclass,regclass,name) line 86 at IF
SQL statement "
        CREATE TEMP TABLE table_diff AS
        SELECT
            T.id,
            T.action
        FROM
            table_version.ver_get_table_differences(
                's_statsnz_ta', 'm_statsnz_ta', 'ogc_fid'
            ) AS T (action CHAR(1), id integer)
        ORDER BY
            T.action,
            T.id;
        "
PL/pgSQL function table_version.ver_executetemplate(text,text[]) line 8 at EXECUTE statement
SQL statement "SELECT table_version.ver_ExecuteTemplate( $sql$
        CREATE TEMP TABLE table_diff AS
        SELECT
            T.id,
            T.action
        FROM
            table_version.ver_get_table_differences(
                '%1%', '%2%', '%3%'
            ) AS T (action CHAR(1), id %4%)
        ORDER BY
            T.action,
            T.id;
        $sql$,
        ARRAY[
            p_original_table::TEXT,
            p_new_table::TEXT,
            p_key_column::TEXT,
            table_version.ver_table_key_datatype(p_original_table, p_key_column)
        ]
    )"
PL/pgSQL function table_version.ver_apply_table_differences(regclass,regclass,name) line 8 at PERFORM
SQL statement "select table_version.ver_apply_table_differences('admin_bdys_import.s_statsnz_ta','admin_bdys_import.m_statsnz_ta','ogc_fid')"
PL/pgSQL function import_admin_boundary(character varying) line 137 at EXECUTE statement
ERROR: type of parameter 26 (integer) does not match that when preparing the plan (character varying)
SQL state: P0001
Context: SQL statement "SELECT table_version.ver_ExecuteTemplate( $sql$
        CREATE TEMP TABLE table_diff AS
        SELECT
            T.id,
            T.action
        FROM
            table_version.ver_get_table_differences(
                '%1%', '%2%', '%3%'
            ) AS T (action CHAR(1), id %4%)
        ORDER BY
            T.action,
            T.id;
        $sql$,
        ARRAY[
            p_original_table::TEXT,
            p_new_table::TEXT,
            p_key_column::TEXT,
            table_version.ver_table_key_datatype(p_original_table, p_key_column)
        ]
    )"
PL/pgSQL function table_version.ver_apply_table_differences(regclass,regclass,name) line 8 at PERFORM
SQL statement "select table_version.ver_apply_table_differences('admin_bdys_import.s_statsnz_ta','admin_bdys_import.m_statsnz_ta','ogc_fid')"
PL/pgSQL function import_admin_boundary(character varying) line 137 at EXECUTE statement

**Comment by palmerj** [comment]
@josephramsay: Are you able to raise this as an issue in the table-version issue tracker https://github.com/linz/postgresql-tableversion/issues/ with a simple reproducible case? e/.g SQL file which creates two tables and a couple of rows that causes the same exception to be thrown.

Thanks!

**Comment by billgeo** [comment]
Hi @josephramsay, can you update on where this one is at?

**Comment by josephramsay** [comment]
Workaround with alternative db driver
