### ISSUE TITLE
admin_bdy branch: add more configuration

### ISSUE THREAD

**Issue by billgeo** [linz/download_ta_bdys#13]
Would be good to make this more configurable rather than hardcoded and also use YAML for configuration.

Things like:

1) Data sources
2) Source -> Target schema mapping
3) Logging email details

**Comment by josephramsay** [comment]
1) Data sources are itemised in the config.ini (pushed as template)
2) Hardcoded in SQL, but still being developed. I can push table mapping to a config (if we expect column defs to change) and run this code in the import script but its a big rewrite and will be less efficient
3) Do we now require users to authenticate to run this script manually? I thought it was a cron job.

I'm detecting scope creep

**Comment by billgeo** [comment]
- [X]  Great. So new sources can be added through the config as well?
- [ ]  Let's review with Ivan via #17 . But yes, fairly likely column defs will change at some point knowing the agencies that manage this data.
- [X]  No scope creep. The tool needs to be able to email a log. If that's done in the cron job, that's fine.

**Comment by josephramsay** [comment]
1) Could be done. Code reads a named file that can be enumerated. Job for later?
2) ... 
3) I read it as "users email details to be logged" rather than "logs sent to email addresses". Okay

**Comment by billgeo** [comment]
Okay updated subtasks.

**Comment by josephramsay** [comment]
config now contains editable table mappings.

legacy code has logger setup with email as output and can be set in config (though this legacy stuff needs a rewrite)... since we'll now be getting users to (initiate)/confirm imports we could do some limited auth

**Comment by josephramsay** [comment]
Superseded with https://github.com/linz/linz-admin-boundaries-uploader
