### ISSUE TITLE
Add index to territorial_authority_grid for AIMS

### ISSUE THREAD

**Issue by billgeo** [linz/download_ta_bdys#14]
additional index needed on territorial_authority_grid table

create index territorial_authority_grid_territorial_authority_ogc_fid_idx on admin_bdys.territorial_authority_grid(territorial_authority_ogc_fid);

https://github.com/linz/AIMS/issues/60#event-655254329

**Comment by ghost** [comment]
@billgeo There is no grid table in the Stats_MB_TA_WKY_yyyymmdd-NEW.zip

**Comment by billgeo** [comment]
You're right. That part is in the BDE processor. Will add an issue there for this.
