### ISSUE TITLE
Add territorial_authority_grid table

### ISSUE THREAD

**Issue by billgeo** [linz/download_ta_bdys#15]
Move the logic to create and maintain the territorial_authority_grid table from the BDE processor to here. See https://github.com/linz/linz_bde_uploader/blob/824f9fad7aafd9538776d06218d602b398d207d8/CHANGELOG.md

**Comment by billgeo** [comment]
Need to also add an additional index needed on territorial_authority_grid table

create index territorial_authority_grid_territorial_authority_ogc_fid_idx on admin_bdys.territorial_authority_grid(territorial_authority_ogc_fid);

linz/AIMS#60 (comment)

**Comment by josephramsay** [comment]
The grid function is built somewhere else. Certainly not in the source data. Isn't this an external task

**Comment by billgeo** [comment]
Yep. It was in the BDE processor but need to move it here where it more naturally sits. Will no longer be in the BDE processor. 

@palmerj can you point Joe at the function he needs to incorporate?

**Comment by palmerj** [comment]
Function is provided in https://github.com/linz/linz-postgresql-functions which is packaged in the LINZ launchpad PPA.

**Comment by josephramsay** [comment]
Done
