### ISSUE TITLE
Change SFTP connection to regular file system mount

### ISSUE THREAD

**Issue by billgeo** [linz/download_ta_bdys#16]
Good news, @josephramsay, can mount the meshblock folder as a CIFS mount. 

See the Wiki:
http://geodeticwiki/Meshblocks

**Comment by josephramsay** [comment]
The SFTP solution is working and deployed on dev. To maintain deadlines I will leave this solution in place and rewrite post launch

**Comment by billgeo** [comment]
Yip. Okay. Will leave this open though until it's done. I'll remove the 1.0 milestone.

**Comment by josephramsay** [comment]
Transition to NFS mount to enable gdal functionality.
