### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by billgeo** [linz/download_ta_bdys#17]
@josephramsay. As discussed, once you've incorporated the fix from the table_version function and got it working again. We will do a code review with @imincik and discuss any improvements that could be made.

**Comment by billgeo** [comment]
@josephramsay, as part of that can you make sure you update all the outstanding issues with current progress please.

**Comment by imincik** [comment]
@billgeo , Joe listens only for @jrlinz . This is his LINZ account for GitHub.

**Comment by josephramsay** [comment]
table_version workaround by using psycopg2

**Comment by strk** [comment]
@imincik should this be closed and moved to review of the new repo ?

**Comment by imincik** [comment]
I don't know.

@billgeo , @jrlinz - do you remember what this issue is about ? At this time PR where not used.

**Comment by imincik** [comment]
There is no real commit from year 2016 in master branch.

**Comment by billgeo** [comment]
I think we can close this. This was to do a code review after Joe made some changes which were done in the new repo I think.
