### ISSUE TITLE
Rewrite and expand for other data

### ISSUE THREAD

**Issue by billgeo** [linz/download_ta_bdys#5]
Needs to be rewritten to also import meshblocks and NZFS boundaries
These may include FTP or CIFS sources.

**Comment by billgeo** [comment]
Documentation describing the design for this can be found at https://linzone/id:A2344322

Will also need to rename this repository to download_admin_bdys and update documentation etc.

**Comment by billgeo** [comment]
Joe can you please give an indication of how long this will take to complete.

**Comment by billgeo** [comment]
@jrlinz, also make sure you replicate the logic in the end_point issue branch of this repo.

**Comment by billgeo** [comment]
@jrlinz as discussed today in AIMS defect review, this tool will need to do basic validation on localities and meshblocks.

**Comment by josephramsay** [comment]
@billgeo pushed admin_bdys branch with first draft of added functionality, awaiting validation matrix from @Deb-Jones

**Comment by josephramsay** [comment]
Update: SFTP impractical, workaround for pexpect/sh commands was access to share. Revert to SFTP?

**Comment by billgeo** [comment]
Not sure what you mean? Are you saying you _can_ use SFTP? That's definitely preferable.

**Comment by ghost** [comment]
We can use SFTP but there were issues. Discussed at the time and you suggested accessing the file share.
1) The standard python SFTP libraries (paramiko and twisted*) are not available on the version of ubuntu on the geoservers so we have to use pexpect which is less secure and a possible maintenance issue.
2) I think this was the reason we needed that no-password account set up. Can't recall the details.

**Comment by palmerj** [comment]
@jrlinz: I think going with the share over the SFTP custom option is the best idea, especially as it makes it possible to more generically write the code to leverage OGR, and place more of the definition of the datasource specifics into the configuration files.

**Comment by billgeo** [comment]
Yip. Using the share sounds fine to me if that's where we are at with SFTP.

**Comment by billgeo** [comment]
@josephramsay, can you confirm that all the new datasources (as per the original design doc) are now configured and working?

**Comment by ghost** [comment]
Reverting to SFTP, in progress
