### ISSUE TITLE
admin_bdy branch: create schema

### ISSUE THREAD

**Issue by billgeo** [linz/download_ta_bdys#7]
Add an option to create the db schema and schema objects, either as empty or do an import straight away.

**Comment by billgeo** [comment]
Need to turn on table revisioning for all tables.

Table DDL and how to set up revisioning can be found here:
https://github.com/billgeo/AIMS-reference-data/tree/master/sql

**Comment by josephramsay** [comment]
There is no need to version import tables and target tables are versioned already. function apply_table_differences() used for this capability

**Comment by billgeo** [comment]
Hi @josephramsay, can you give an update on where we are at with the stuff in the originial commment. Option to create/drop schema etc.

**Comment by josephramsay** [comment]
This was built in from from beginning as test feature with temp schema getting created/deleted on each run. Will make this permanent as feature to allow user validation. Option to create/drop can be made optional though once data is imported we wont need the temp stuff anymore.

**Comment by josephramsay** [comment]
Superseded with https://github.com/linz/linz-admin-boundaries-uploader
