### ISSUE TITLE
admin_bdy branch: filter/map fields

### ISSUE THREAD

**Issue by billgeo** [linz/download_ta_bdys#8]
Data has to be filtered/mapped to more useable field names.

Details can be found here:
https://github.com/billgeo/AIMS-reference-data/blob/master/import_localities.sh
https://github.com/billgeo/AIMS-reference-data/blob/master/import_meshblocks.sh

**Comment by josephramsay** [comment]
Mapping is being done to existing data assuming this is final format and considering its what AIMS is using already
