### ISSUE TITLE
admin_bdy branch: add basic validation

### ISSUE THREAD

**Issue by billgeo** [linz/download_ta_bdys#9]
Capturing this as a separate issue. Need to add basic validation rules for admin data imports.

**Comment by billgeo** [comment]
I will collate the current validation from e-Spatial docs for review.

**Comment by billgeo** [comment]
No docs needed to review. Just check for valid geometries, coordinate system conversions and null IDs etc.

**Comment by josephramsay** [comment]
Running check functions from original download_ta_bdys plus the 7 digit code check thats been discussed before. Which new validations specifically do you want?

**Comment by billgeo** [comment]
What are the original download_ta_bdys checks? And are you running them on all the relevant tables?

**Comment by josephramsay** [comment]
The original ones are not so much checks as fixes, see shift_geom, esri_fix etc. I have 1 validation as mentioned in meetings, the 7 digit code length
